services:
  db:
    image: mysql:latest
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: vienna
      MYSQL_DATABASE: taller_persona
      MYSQL_USER: bowie
      MYSQL_PASSWORD: vienna
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/taller_persona
      MYSQL_ROOT_PASSWORD: vienna
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge